---
- hosts: all
  sudo: yes
  gather_facts: yes

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-debian
    - geerlingguy.java
    - geerlingguy.elasticsearch
    - geerlingguy.nginx
    - geerlingguy.nodejs
    - geerlingguy.redis
    - TalLannder.ZooKeeper
    - nowait.rabbitmq

  tasks:
    - name: Ancillary tooling is present
      apt: "name={{ item }} state=installed"
      with_items:
        - rabbitmq-server
        - git
        - wget
        - curl
        - vim
